# Generated by Django 2.1 on 2018-11-07 00:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 7, 0, 4, 46, 54354)),
        ),
    ]
