# Generated by Django 2.1 on 2018-11-07 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0002_auto_20181107_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='timestamp',
        ),
    ]
