# Generated by Django 2.1 on 2018-11-07 00:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0003_remove_note_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 7, 0, 11, 14, 26316)),
        ),
    ]
